// Mocks generated by Mockito 5.4.4 from annotations
// in login_app/test/widget_tests/pokemon_game_page_basic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:login_app/src/data/datasources/pokemon_remote_datasource.dart'
    as _i2;
import 'package:login_app/src/domain/entities/user.dart' as _i5;
import 'package:login_app/src/domain/repositories/auth_repository.dart' as _i10;
import 'package:login_app/src/domain/repositories/pokemon_repository.dart'
    as _i4;
import 'package:login_app/src/domain/usecases/save_game_score.dart' as _i3;
import 'package:login_app/src/domain/usecases/sign_in.dart' as _i7;
import 'package:login_app/src/domain/usecases/sign_out.dart' as _i9;
import 'package:login_app/src/domain/usecases/sign_up.dart' as _i8;
import 'package:login_app/src/presentation/bloc/auth_bloc.dart' as _i16;
import 'package:login_app/src/presentation/bloc/auth_event.dart' as _i17;
import 'package:login_app/src/presentation/bloc/auth_state.dart' as _i11;
import 'package:login_app/src/presentation/bloc/pokemon_game_bloc.dart' as _i12;
import 'package:login_app/src/presentation/bloc/pokemon_game_event.dart'
    as _i14;
import 'package:login_app/src/presentation/bloc/pokemon_game_state.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.PokemonRemoteDataSource {
  _FakePokemonRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveGameScore_1 extends _i1.SmartFake implements _i3.SaveGameScore {
  _FakeSaveGameScore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonRepository_2 extends _i1.SmartFake
    implements _i4.PokemonRepository {
  _FakePokemonRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_3 extends _i1.SmartFake implements _i5.User {
  _FakeUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonGameState_4 extends _i1.SmartFake
    implements _i6.PokemonGameState {
  _FakePokemonGameState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignIn_5 extends _i1.SmartFake implements _i7.SignIn {
  _FakeSignIn_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUp_6 extends _i1.SmartFake implements _i8.SignUp {
  _FakeSignUp_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignOut_7 extends _i1.SmartFake implements _i9.SignOut {
  _FakeSignOut_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_8 extends _i1.SmartFake
    implements _i10.AuthRepository {
  _FakeAuthRepository_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthState_9 extends _i1.SmartFake implements _i11.AuthState {
  _FakeAuthState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonGameBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonGameBloc extends _i1.Mock implements _i12.PokemonGameBloc {
  MockPokemonGameBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRemoteDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakePokemonRemoteDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.PokemonRemoteDataSource);

  @override
  _i3.SaveGameScore get saveGameScore => (super.noSuchMethod(
        Invocation.getter(#saveGameScore),
        returnValue: _FakeSaveGameScore_1(
          this,
          Invocation.getter(#saveGameScore),
        ),
      ) as _i3.SaveGameScore);

  @override
  _i4.PokemonRepository get pokemonRepository => (super.noSuchMethod(
        Invocation.getter(#pokemonRepository),
        returnValue: _FakePokemonRepository_2(
          this,
          Invocation.getter(#pokemonRepository),
        ),
      ) as _i4.PokemonRepository);

  @override
  _i5.User get currentUser => (super.noSuchMethod(
        Invocation.getter(#currentUser),
        returnValue: _FakeUser_3(
          this,
          Invocation.getter(#currentUser),
        ),
      ) as _i5.User);

  @override
  _i6.PokemonGameState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePokemonGameState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.PokemonGameState);

  @override
  _i13.Stream<_i6.PokemonGameState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i6.PokemonGameState>.empty(),
      ) as _i13.Stream<_i6.PokemonGameState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i14.PokemonGameEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i14.PokemonGameEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.PokemonGameState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i14.PokemonGameEvent>(
    _i15.EventHandler<E, _i6.PokemonGameState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i14.PokemonGameEvent, _i6.PokemonGameState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i15.Change<_i6.PokemonGameState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i16.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.SignIn get signIn => (super.noSuchMethod(
        Invocation.getter(#signIn),
        returnValue: _FakeSignIn_5(
          this,
          Invocation.getter(#signIn),
        ),
      ) as _i7.SignIn);

  @override
  _i8.SignUp get signUp => (super.noSuchMethod(
        Invocation.getter(#signUp),
        returnValue: _FakeSignUp_6(
          this,
          Invocation.getter(#signUp),
        ),
      ) as _i8.SignUp);

  @override
  _i9.SignOut get signOut => (super.noSuchMethod(
        Invocation.getter(#signOut),
        returnValue: _FakeSignOut_7(
          this,
          Invocation.getter(#signOut),
        ),
      ) as _i9.SignOut);

  @override
  _i10.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_8(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i10.AuthRepository);

  @override
  _i11.AuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAuthState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.AuthState);

  @override
  _i13.Stream<_i11.AuthState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i11.AuthState>.empty(),
      ) as _i13.Stream<_i11.AuthState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i17.AuthEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i17.AuthEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.AuthState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i17.AuthEvent>(
    _i15.EventHandler<E, _i11.AuthState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i15.Transition<_i17.AuthEvent, _i11.AuthState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i15.Change<_i11.AuthState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
